### PR TITLE
Facebook login

### PR DESCRIPTION
**Pull request by IgnacioColuccio**
### Summary
- Added login with Facebook
- Refactored login with Google so both would share most code.
- Changed session store to active_record_store, or else Facebook login would break.

### Trello card
https://trello.com/c/1FYmrZWz/22-integrar-el-blog-con-facebook-login

### Test plan
1. While signed out, sign in using Facebook
2. It should ask for permissions
3. After accepting the prompt, you should be logged in with your Facebook account's e-mail (unless the account has no configured e-mail but only phone, in that case it should redirect to the normal sign up page)
4. Sign out
5. Sign in using Google, it should still work (even with the same e-mail)

### CODE REVIEW

**Comment by Dinuuu** [comment]
I think you have some git issues here, because the first commit you already have it in #12 , maybe you are missing a Rebase here

**Comment by IgnacioColuccio** [comment]
Maybe I should have skipped it? The commit is just whitespace: https://github.com/wolox-training/igc-rails/commit/78b4ea1c02ebcff141eff358d9b5daa016cc5cb7

**Comment by IgnacioColuccio** [comment]
Squashed them into one commit

**Comment by Dinuuu** [comment]
When we squash commits we generally use just one comment (not all the comments of the different commits we squashed), this is just informative, try to do that next time.

:+1:

**Comment by IgnacioColuccio** [comment]
Alright!

**Pull request merged**
