### PR TITLE
Added CodeClimate configuration + badge to readme

### PR DESCRIPTION
**Pull request by IgnacioColuccio**
### Summary
- Added CodeClimate

###Trello card 
https://trello.com/c/6wtfGj0Y/18-configurar-codeclimate

###Test plan
See badge

### CODE REVIEW

**Comment by IgnacioColuccio** [comment]
Falta code coverage

**Comment by Dinuuu** [comment]
Be careful here, you messed up something with git, you got a lot of commits that don't belongs here. Check if you can fix this

**Comment by IgnacioColuccio** [comment]
It was fixed by merging pundit into development and rebasing this into development.

**Comment by Dinuuu** [comment]
:+1:

**Pull request merged**
